### ISSUE TITLE
Bug when normalizing #4C0B5F

### ISSUE THREAD

**Issue by jbarbede** [kolory/color-utilities#10]
Hey, It looks like the 0 has been removed from #4C0B5F by normalization and it throws some error.

```javascript
TypeError: Using invalid hex color value. Used "#4cb5f" but only #RGB and #RRGGBB are allowed.
    at ColorUtilities.throwInvalidHexColor (http://.../build/main.js:205282:15)
    at ColorUtilities.throwIfInvalidHexColor (http://.../build/main.js:205286:18)
    at ColorUtilities.normalizeHexColor (http://.../build/main.js:205257:14)
    at ColorUtilities.convertValuesToHex (http://.../build/main.js:205109:21)
    at ColorUtilities.convertRawValuesTo (http://.../build/main.js:205099:29)
    at Color.getColor (http://.../build/main.js:205487:32)
    at Color.get [as hex] (http://.../build/main.js:205398:25)
    at Color.calculateContrastTo (http://.../build/main.js:205467:59)
    at http://.../build/main.js:204980:39
    at Array.map (native)
    at MatchStyleDirective.getStyleWithHighestContrast (http://.../build/main.js:204977:14)
    at MatchStyleDirective.handleBackgroundChange (http://.../build/main.js:204958:26)
    at MatchStyleDirective.ngOnChanges (http://.../build/main.js:204952:18)
    at Wrapper_MatchStyleDirective.ngDoCheck (/MatchStyleModule/MatchStyleDirective/wrapper.ngfactory.js:50:18)
    at View_FvItemMatrixLabelModal2.detectChangesInternal (/AppModule/FvItemMatrixLabelModal/component.ngfactory.js:50:33)
```

**Comment by mateuszkocz** [comment]
Thanks for reporting the issue. There was a problem with colors whose one of the RGB value was smaller than 16. It got converted to a single hex value instead of the value padded with "0".

The fix is included in the version 0.0.3 and published on npm.
